const Switcher = [{
    name:"KEVIN O'NEILL",
    start:"5:30",
    hostler:"",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"ANGEL ROSARIO",
    start:"5:00",
    hostler:"",
    quad:"Rec/Chill",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"JAMES SELBY",
    start:"5:45",
    hostler:"",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"ROBERT MCCLANAHAN",
    start:"5:30",
    hostler:"",
    quad:"Rec/Chill",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"RICH LOOCK",
    start:"5:45",
    hostler:"9",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"DAN ALONZO",
    start:"5:00",
    hostler:"14",
    quad:"",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"JUAN RUIZ",
    start:"5:45",
    hostler:"15",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"CARLOS GUERRERO",
    start:"5:45",
    hostler:"4",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"TERRANCE UPCHURCH",
    start:"5:45",
    hostler:"2",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"NICK MOLINO",
    start:"5:45",
    hostler:"3",
    quad:"",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"IVAN ROBINSON",
    start:"5:45",
    hostler:"8",
    quad:"Rec/Chill",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"DOMINIK KON",
    start:"5:45",
    hostler:"10",
    quad:"shp/plt",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"VICTOR CRUZ",
    start:"6:00",
    hostler:"7",
    quad:"Rec/Chill",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"ERIK ROSADO",
    start:"5:45",
    hostler:"1",
    quad:"",
    category:"reg",
    off:"Sat/Sun"
},
  {  name:"THOMAS BEERS",
    start:"5:45",
    hostler:"",
    quad:"",
    category:"reg",
    off:"Sat/Sun"
},
]
export default Switcher