const Switcher = [{
    name:"KEVIN O'NEILL",
    start:"5:30",
    hostler:"9",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"ANGEL ROSARIO",
    start:"5:00",
    hostler:"12",
    quad:"Rec/Chill",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"JAMES SELBY",
    start:"5:45",
    hostler:"5",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"ROBERT MCCLANAHAN",
    start:"5:30",
    hostler:"13",
    quad:"Rec/Chill",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"RICH LOOCK",
    start:"5:45",
    hostler:"6",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"DAN ALONZO",
    start:"5:00",
    hostler:"14",
    quad:"",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"JUAN RUIZ",
    start:"5:45",
    hostler:"15",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"CARLOS GUERRERO",
    start:"5:45",
    hostler:"4",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"TERRANCE UPCHURCH",
    start:"5:45",
    hostler:"2",
    quad:"shp/plt",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"NICK MOLINO",
    start:"5:45",
    hostler:"3",
    quad:"",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"IVAN ROBINSON",
    start:"5:45",
    hostler:"8",
    quad:"Rec/Chill",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"DOMINIK KON",
    start:"5:45",
    hostler:"10",
    quad:"shp/plt",
    category:"permanent",
    off:"Tue/Sat"
},
  {  name:"VICTOR CRUZ",
    start:"6:00",
    hostler:"7",
    quad:"Rec/Chill",
    category:"permanent",
    off:"Sat/Sun"
},
  {  name:"ERIK ROSADO",
    start:"5:45",
    hostler:"1",
    quad:"",
    category:"permanent",
    off:"Sun/Thu"
},
  {  name:"THOMAS BEERS",
    start:"5:45",
    hostler:"",
    quad:"",
    category:"permanent",
    off:"Sat/Sun"
},
// cover switchers
{  name:"MARK TAYLOR",
start:"5:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"LAZARO BAEZ",
start:"5:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"TERREL THOMPSON",
start:"8:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"JEFF GIVENS",
start:"8:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"BRIAN PULLEN",
start:"8:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"DAVID TOMEI",
start:"8:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"MAURICIO QUINTERO",
start:"9:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"JEFF SHELL",
start:"9:00",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"MIKE MAYID",
start:"5:45",
hostler:"",
quad:"",
category:"cover",
off:"Thu/Fri"
},
{  name:"BEN CUNNINGHAM",
start:"12:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"TED MAROUSIS",
start:"12:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"LLOYD TOWNES",
start:"12:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"LEONEL VARGAS",
start:"12:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"VICTOR BLOT",
start:"12:45",
hostler:"",
quad:"",
category:"cover",
off:"Sat/Sun"
},
{  name:"JOSE ALMADA",
start:"1:45",
hostler:"",
quad:"",
category:"cover",
off:"Sun/Mon"
},
{  name:"ERIC LUPO",
start:"2:00",
hostler:"",
quad:"",
category:"cover",
off:"Fri/Sat"
},
{  name:"AURELIO MIRANDA",
start:"2:00",
hostler:"",
quad:"",
category:"cover",
off:"Fri/Sat"
},
]
export default Switcher